apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default.redis
  namespace: default
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: customer
  - from:
    - podSelector:
        matchLabels:
          app: indexer
  podSelector:
    matchLabels:
      app: redis