apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: default
  labels:
    app: admin
spec:
  selector:
    app: admin
  ports:
  - name: http
    port: 80
    targetPort: 8085
    protocol: TCP
  type: #SVC_TYPE#