apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer  
  template:
    metadata:
      labels:
        app: customer
    spec:
      serviceAccountName: customer
      containers:
      - name: customer
        image: tufinim/generic-bank
        ports:
        - containerPort: 8085
        env:
        - name: DB_URL
          value: "http://redis"
        - name: BALANCE_URL
          value: "http://balance"
        - name: MODE
          value: "customer"
